import React, { Component } from 'react';

import MainNavi from '../MainNavi/MainNavi';
import planesgreet from './planesgreet.svg';
import planemap from './PlaneMap.png';
import selnatamap from './selnatamap.png';

class Planes extends Component {
    componentDidMount() {
        window.scrollTo(0, 0)
      }
    render() {
        return (
            <div className="planes-container">
                <div className="para-one">
                    <img src={planesgreet} alt="greetings"/>
                </div>
                <div className="gradient-header">
                    <h1>The Planar System</h1>
                </div>
                <div className="para-three">
                    <div className="plane-explination">
                        <h3>Getting from Place to Place</h3>
                        <p>While the ten planes of the Syndicate are all connected, there are certain paths you need to travel to get to certain planes. Some planar gates are closed. For example, Minereth to Vapor is impassable.</p>
                    </div>
                    <div className="plane-map">
                        <img src={planemap} alt="Planar  Map" />
                    </div>
                </div>
                <div className="gradient-header">
                    <h1>The Planes</h1>
                </div>
                <div className="planer-nav">
                    <ul>
                        <li><a href="#selnata">Selnata</a></li>
                        <li><a href='#lanaetu'>Lanae'tu</a></li>
                        <li><a href='#daervyn'>Daervyn</a></li>
                        <li><a href='#minereth'>Minereth</a></li>
                        <li><a href='#sorenthis'>Sorenthis</a></li>
                        <li><a href='#vayle'>Vayle</a></li>
                        <li><a href='#ofuria'>Ofuria</a></li>
                        <li><a href='#vapor'>Vapor</a></li>
                        <li><a href='#farkath'>Farkath Vilga</a></li>
                        <li><a href='#tempestia'>Tempestia</a></li>
                    </ul>
                </div>
                <div className="planer-block" id="selnata">
                    <div className="planar-map">
                        <img src={selnatamap} alt="plane" />
                    </div>
                    <h3>Selnata</h3>
                    <div className="planar-description">
                        <p>By far the largest and most populated of the sixth plane’s continents, Selnata consists of several sub-regions, all with differing cultures and economic structures. Though Selnata was once ruled by a monarchy, it is now controlled by the guilds. The Guild Council - a loose parliament of the most powerful guild lords - has governed Selnata for the last two centuries and oversees all trade between the sixth plane and its neighbors.</p>
                        <p>For more information on the continents and countries on Selnata, <a href="https://docs.google.com/document/d/1VtJr1-bnY6Ads_SHJdqaoHbJZIywXTwYgcGvqCNcLLE">check out the docs.</a></p>
                    </div>
                </div>
                <div className="planer-block" id="lanaetu">
                    <div className="planar-map"><img src={planemap} alt="plane" /></div>
                    <div className="planar-description">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et est ante. Nunc porttitor, diam ac rhoncus pulvinar, mi mauris elementum dui, ut feugiat tellus ex eget ex. Duis vitae ultrices orci, id commodo sapien. Integer sed vehicula nisl. Suspendisse tincidunt ultrices nisi. Aenean dictum arcu vel nisl aliquam, quis imperdiet est eleifend. Nam gravida ligula turpis, ac pulvinar nisl vulputate id. Maecenas ut tempus eros. Duis tempor malesuada lorem, a accumsan diam condimentum non. Suspendisse vitae felis pretium, ultricies lacus quis, convallis libero. Donec ut accumsan justo, a facilisis quam. Sed blandit posuere odio. Quisque ante arcu, finibus eget commodo eu, tempor ut urna. Suspendisse potenti. Aliquam et tempus mauris. Proin nec commodo arcu. Fusce id fermentum est. Nam scelerisque dapibus elit non facilisis. Phasellus vitae massa bibendum, molestie elit non, consequat sapien. Pellentesque dignissim pretium nisi, vel porta velit porttitor vitae. Ut varius ex tellus, porta elementum massa mattis in. Aliquam erat volutpat. Integer euismod odio in urna accumsan auctor. Morbi pretium augue a erat accumsan vestibulum. Aliquam ac nibh fermentum, aliquet lectus at, convallis sapien. Cras eros enim, tempus vitae mi ac, molestie feugiat magna. Phasellus vitae ante facilisis, imperdiet mi porttitor, euismod justo. Morbi scelerisque scelerisque ante at ultricies. Donec pellentesque mattis augue eu sollicitudin. Curabitur consectetur erat id dui feugiat, a viverra ex egestas. Pellentesque nec sagittis mauris, tincidunt facilisis odio. Mauris neque lacus, vulputate at sapien quis, consequat iaculis tortor. Maecenas molestie, leo in consequat feugiat, nibh magna ultricies massa, ut feugiat tortor ligula vulputate sapien. Sed mi lacus, gravida sed tincidunt at, venenatis eget eros. Ut risus ex, cursus at elit hendrerit, semper ultrices tellus. Maecenas porttitor fringilla sapien, vel vulputate mi lacinia et. Quisque venenatis orci vel magna placerat maximus. Cras bibendum felis ac bibendum eleifend. Suspendisse ullamcorper dictum leo, in ornare turpis dignissim eget.</p>
                    </div>
                </div>
                <div className="planer-block" id="daervyn">
                    <div className="planar-map"><img src={planemap} alt="plane" /></div>
                    <div className="planar-description">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et est ante. Nunc porttitor, diam ac rhoncus pulvinar, mi mauris elementum dui, ut feugiat tellus ex eget ex. Duis vitae ultrices orci, id commodo sapien. Integer sed vehicula nisl. Suspendisse tincidunt ultrices nisi. Aenean dictum arcu vel nisl aliquam, quis imperdiet est eleifend. Nam gravida ligula turpis, ac pulvinar nisl vulputate id. Maecenas ut tempus eros. Duis tempor malesuada lorem, a accumsan diam condimentum non. Suspendisse vitae felis pretium, ultricies lacus quis, convallis libero. Donec ut accumsan justo, a facilisis quam. Sed blandit posuere odio. Quisque ante arcu, finibus eget commodo eu, tempor ut urna. Suspendisse potenti. Aliquam et tempus mauris. Proin nec commodo arcu. Fusce id fermentum est. Nam scelerisque dapibus elit non facilisis. Phasellus vitae massa bibendum, molestie elit non, consequat sapien. Pellentesque dignissim pretium nisi, vel porta velit porttitor vitae. Ut varius ex tellus, porta elementum massa mattis in. Aliquam erat volutpat. Integer euismod odio in urna accumsan auctor. Morbi pretium augue a erat accumsan vestibulum. Aliquam ac nibh fermentum, aliquet lectus at, convallis sapien. Cras eros enim, tempus vitae mi ac, molestie feugiat magna. Phasellus vitae ante facilisis, imperdiet mi porttitor, euismod justo. Morbi scelerisque scelerisque ante at ultricies. Donec pellentesque mattis augue eu sollicitudin. Curabitur consectetur erat id dui feugiat, a viverra ex egestas. Pellentesque nec sagittis mauris, tincidunt facilisis odio. Mauris neque lacus, vulputate at sapien quis, consequat iaculis tortor. Maecenas molestie, leo in consequat feugiat, nibh magna ultricies massa, ut feugiat tortor ligula vulputate sapien. Sed mi lacus, gravida sed tincidunt at, venenatis eget eros. Ut risus ex, cursus at elit hendrerit, semper ultrices tellus. Maecenas porttitor fringilla sapien, vel vulputate mi lacinia et. Quisque venenatis orci vel magna placerat maximus. Cras bibendum felis ac bibendum eleifend. Suspendisse ullamcorper dictum leo, in ornare turpis dignissim eget.</p>
                    </div>
                </div>
                <div className="planer-block" id="minereth">
                    <div className="planar-map"><img src={planemap} alt="plane" /></div>
                    <div className="planar-description">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et est ante. Nunc porttitor, diam ac rhoncus pulvinar, mi mauris elementum dui, ut feugiat tellus ex eget ex. Duis vitae ultrices orci, id commodo sapien. Integer sed vehicula nisl. Suspendisse tincidunt ultrices nisi. Aenean dictum arcu vel nisl aliquam, quis imperdiet est eleifend. Nam gravida ligula turpis, ac pulvinar nisl vulputate id. Maecenas ut tempus eros. Duis tempor malesuada lorem, a accumsan diam condimentum non. Suspendisse vitae felis pretium, ultricies lacus quis, convallis libero. Donec ut accumsan justo, a facilisis quam. Sed blandit posuere odio. Quisque ante arcu, finibus eget commodo eu, tempor ut urna. Suspendisse potenti. Aliquam et tempus mauris. Proin nec commodo arcu. Fusce id fermentum est. Nam scelerisque dapibus elit non facilisis. Phasellus vitae massa bibendum, molestie elit non, consequat sapien. Pellentesque dignissim pretium nisi, vel porta velit porttitor vitae. Ut varius ex tellus, porta elementum massa mattis in. Aliquam erat volutpat. Integer euismod odio in urna accumsan auctor. Morbi pretium augue a erat accumsan vestibulum. Aliquam ac nibh fermentum, aliquet lectus at, convallis sapien. Cras eros enim, tempus vitae mi ac, molestie feugiat magna. Phasellus vitae ante facilisis, imperdiet mi porttitor, euismod justo. Morbi scelerisque scelerisque ante at ultricies. Donec pellentesque mattis augue eu sollicitudin. Curabitur consectetur erat id dui feugiat, a viverra ex egestas. Pellentesque nec sagittis mauris, tincidunt facilisis odio. Mauris neque lacus, vulputate at sapien quis, consequat iaculis tortor. Maecenas molestie, leo in consequat feugiat, nibh magna ultricies massa, ut feugiat tortor ligula vulputate sapien. Sed mi lacus, gravida sed tincidunt at, venenatis eget eros. Ut risus ex, cursus at elit hendrerit, semper ultrices tellus. Maecenas porttitor fringilla sapien, vel vulputate mi lacinia et. Quisque venenatis orci vel magna placerat maximus. Cras bibendum felis ac bibendum eleifend. Suspendisse ullamcorper dictum leo, in ornare turpis dignissim eget.</p>
                    </div>
                </div>
                <div className="planer-block" id="sorenthis">
                    <div className="planar-map"><img src={planemap} alt="plane" /></div>
                    <div className="planar-description">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et est ante. Nunc porttitor, diam ac rhoncus pulvinar, mi mauris elementum dui, ut feugiat tellus ex eget ex. Duis vitae ultrices orci, id commodo sapien. Integer sed vehicula nisl. Suspendisse tincidunt ultrices nisi. Aenean dictum arcu vel nisl aliquam, quis imperdiet est eleifend. Nam gravida ligula turpis, ac pulvinar nisl vulputate id. Maecenas ut tempus eros. Duis tempor malesuada lorem, a accumsan diam condimentum non. Suspendisse vitae felis pretium, ultricies lacus quis, convallis libero. Donec ut accumsan justo, a facilisis quam. Sed blandit posuere odio. Quisque ante arcu, finibus eget commodo eu, tempor ut urna. Suspendisse potenti. Aliquam et tempus mauris. Proin nec commodo arcu. Fusce id fermentum est. Nam scelerisque dapibus elit non facilisis. Phasellus vitae massa bibendum, molestie elit non, consequat sapien. Pellentesque dignissim pretium nisi, vel porta velit porttitor vitae. Ut varius ex tellus, porta elementum massa mattis in. Aliquam erat volutpat. Integer euismod odio in urna accumsan auctor. Morbi pretium augue a erat accumsan vestibulum. Aliquam ac nibh fermentum, aliquet lectus at, convallis sapien. Cras eros enim, tempus vitae mi ac, molestie feugiat magna. Phasellus vitae ante facilisis, imperdiet mi porttitor, euismod justo. Morbi scelerisque scelerisque ante at ultricies. Donec pellentesque mattis augue eu sollicitudin. Curabitur consectetur erat id dui feugiat, a viverra ex egestas. Pellentesque nec sagittis mauris, tincidunt facilisis odio. Mauris neque lacus, vulputate at sapien quis, consequat iaculis tortor. Maecenas molestie, leo in consequat feugiat, nibh magna ultricies massa, ut feugiat tortor ligula vulputate sapien. Sed mi lacus, gravida sed tincidunt at, venenatis eget eros. Ut risus ex, cursus at elit hendrerit, semper ultrices tellus. Maecenas porttitor fringilla sapien, vel vulputate mi lacinia et. Quisque venenatis orci vel magna placerat maximus. Cras bibendum felis ac bibendum eleifend. Suspendisse ullamcorper dictum leo, in ornare turpis dignissim eget.</p>
                    </div>
                </div>
                <div className="planer-block" id="vayle">
                    <div className="planar-map"><img src={planemap} alt="plane" /></div>
                    <div className="planar-description">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et est ante. Nunc porttitor, diam ac rhoncus pulvinar, mi mauris elementum dui, ut feugiat tellus ex eget ex. Duis vitae ultrices orci, id commodo sapien. Integer sed vehicula nisl. Suspendisse tincidunt ultrices nisi. Aenean dictum arcu vel nisl aliquam, quis imperdiet est eleifend. Nam gravida ligula turpis, ac pulvinar nisl vulputate id. Maecenas ut tempus eros. Duis tempor malesuada lorem, a accumsan diam condimentum non. Suspendisse vitae felis pretium, ultricies lacus quis, convallis libero. Donec ut accumsan justo, a facilisis quam. Sed blandit posuere odio. Quisque ante arcu, finibus eget commodo eu, tempor ut urna. Suspendisse potenti. Aliquam et tempus mauris. Proin nec commodo arcu. Fusce id fermentum est. Nam scelerisque dapibus elit non facilisis. Phasellus vitae massa bibendum, molestie elit non, consequat sapien. Pellentesque dignissim pretium nisi, vel porta velit porttitor vitae. Ut varius ex tellus, porta elementum massa mattis in. Aliquam erat volutpat. Integer euismod odio in urna accumsan auctor. Morbi pretium augue a erat accumsan vestibulum. Aliquam ac nibh fermentum, aliquet lectus at, convallis sapien. Cras eros enim, tempus vitae mi ac, molestie feugiat magna. Phasellus vitae ante facilisis, imperdiet mi porttitor, euismod justo. Morbi scelerisque scelerisque ante at ultricies. Donec pellentesque mattis augue eu sollicitudin. Curabitur consectetur erat id dui feugiat, a viverra ex egestas. Pellentesque nec sagittis mauris, tincidunt facilisis odio. Mauris neque lacus, vulputate at sapien quis, consequat iaculis tortor. Maecenas molestie, leo in consequat feugiat, nibh magna ultricies massa, ut feugiat tortor ligula vulputate sapien. Sed mi lacus, gravida sed tincidunt at, venenatis eget eros. Ut risus ex, cursus at elit hendrerit, semper ultrices tellus. Maecenas porttitor fringilla sapien, vel vulputate mi lacinia et. Quisque venenatis orci vel magna placerat maximus. Cras bibendum felis ac bibendum eleifend. Suspendisse ullamcorper dictum leo, in ornare turpis dignissim eget.</p>
                    </div>
                </div>
                <div className="planer-block" id="ofuria">
                    <div className="planar-map"><img src={planemap} alt="plane" /></div>
                    <div className="planar-description">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et est ante. Nunc porttitor, diam ac rhoncus pulvinar, mi mauris elementum dui, ut feugiat tellus ex eget ex. Duis vitae ultrices orci, id commodo sapien. Integer sed vehicula nisl. Suspendisse tincidunt ultrices nisi. Aenean dictum arcu vel nisl aliquam, quis imperdiet est eleifend. Nam gravida ligula turpis, ac pulvinar nisl vulputate id. Maecenas ut tempus eros. Duis tempor malesuada lorem, a accumsan diam condimentum non. Suspendisse vitae felis pretium, ultricies lacus quis, convallis libero. Donec ut accumsan justo, a facilisis quam. Sed blandit posuere odio. Quisque ante arcu, finibus eget commodo eu, tempor ut urna. Suspendisse potenti. Aliquam et tempus mauris. Proin nec commodo arcu. Fusce id fermentum est. Nam scelerisque dapibus elit non facilisis. Phasellus vitae massa bibendum, molestie elit non, consequat sapien. Pellentesque dignissim pretium nisi, vel porta velit porttitor vitae. Ut varius ex tellus, porta elementum massa mattis in. Aliquam erat volutpat. Integer euismod odio in urna accumsan auctor. Morbi pretium augue a erat accumsan vestibulum. Aliquam ac nibh fermentum, aliquet lectus at, convallis sapien. Cras eros enim, tempus vitae mi ac, molestie feugiat magna. Phasellus vitae ante facilisis, imperdiet mi porttitor, euismod justo. Morbi scelerisque scelerisque ante at ultricies. Donec pellentesque mattis augue eu sollicitudin. Curabitur consectetur erat id dui feugiat, a viverra ex egestas. Pellentesque nec sagittis mauris, tincidunt facilisis odio. Mauris neque lacus, vulputate at sapien quis, consequat iaculis tortor. Maecenas molestie, leo in consequat feugiat, nibh magna ultricies massa, ut feugiat tortor ligula vulputate sapien. Sed mi lacus, gravida sed tincidunt at, venenatis eget eros. Ut risus ex, cursus at elit hendrerit, semper ultrices tellus. Maecenas porttitor fringilla sapien, vel vulputate mi lacinia et. Quisque venenatis orci vel magna placerat maximus. Cras bibendum felis ac bibendum eleifend. Suspendisse ullamcorper dictum leo, in ornare turpis dignissim eget.</p>
                    </div>
                </div>
                <div className="planer-block" id="vapor">
                    <div className="planar-map"><img src={planemap} alt="plane" /></div>
                    <div className="planar-description">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et est ante. Nunc porttitor, diam ac rhoncus pulvinar, mi mauris elementum dui, ut feugiat tellus ex eget ex. Duis vitae ultrices orci, id commodo sapien. Integer sed vehicula nisl. Suspendisse tincidunt ultrices nisi. Aenean dictum arcu vel nisl aliquam, quis imperdiet est eleifend. Nam gravida ligula turpis, ac pulvinar nisl vulputate id. Maecenas ut tempus eros. Duis tempor malesuada lorem, a accumsan diam condimentum non. Suspendisse vitae felis pretium, ultricies lacus quis, convallis libero. Donec ut accumsan justo, a facilisis quam. Sed blandit posuere odio. Quisque ante arcu, finibus eget commodo eu, tempor ut urna. Suspendisse potenti. Aliquam et tempus mauris. Proin nec commodo arcu. Fusce id fermentum est. Nam scelerisque dapibus elit non facilisis. Phasellus vitae massa bibendum, molestie elit non, consequat sapien. Pellentesque dignissim pretium nisi, vel porta velit porttitor vitae. Ut varius ex tellus, porta elementum massa mattis in. Aliquam erat volutpat. Integer euismod odio in urna accumsan auctor. Morbi pretium augue a erat accumsan vestibulum. Aliquam ac nibh fermentum, aliquet lectus at, convallis sapien. Cras eros enim, tempus vitae mi ac, molestie feugiat magna. Phasellus vitae ante facilisis, imperdiet mi porttitor, euismod justo. Morbi scelerisque scelerisque ante at ultricies. Donec pellentesque mattis augue eu sollicitudin. Curabitur consectetur erat id dui feugiat, a viverra ex egestas. Pellentesque nec sagittis mauris, tincidunt facilisis odio. Mauris neque lacus, vulputate at sapien quis, consequat iaculis tortor. Maecenas molestie, leo in consequat feugiat, nibh magna ultricies massa, ut feugiat tortor ligula vulputate sapien. Sed mi lacus, gravida sed tincidunt at, venenatis eget eros. Ut risus ex, cursus at elit hendrerit, semper ultrices tellus. Maecenas porttitor fringilla sapien, vel vulputate mi lacinia et. Quisque venenatis orci vel magna placerat maximus. Cras bibendum felis ac bibendum eleifend. Suspendisse ullamcorper dictum leo, in ornare turpis dignissim eget.</p>
                    </div>
                </div>
                <div className="planer-block" id="farkath">
                    <div className="planar-map"><img src={planemap} alt="plane" /></div>
                    <div className="planar-description">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et est ante. Nunc porttitor, diam ac rhoncus pulvinar, mi mauris elementum dui, ut feugiat tellus ex eget ex. Duis vitae ultrices orci, id commodo sapien. Integer sed vehicula nisl. Suspendisse tincidunt ultrices nisi. Aenean dictum arcu vel nisl aliquam, quis imperdiet est eleifend. Nam gravida ligula turpis, ac pulvinar nisl vulputate id. Maecenas ut tempus eros. Duis tempor malesuada lorem, a accumsan diam condimentum non. Suspendisse vitae felis pretium, ultricies lacus quis, convallis libero. Donec ut accumsan justo, a facilisis quam. Sed blandit posuere odio. Quisque ante arcu, finibus eget commodo eu, tempor ut urna. Suspendisse potenti. Aliquam et tempus mauris. Proin nec commodo arcu. Fusce id fermentum est. Nam scelerisque dapibus elit non facilisis. Phasellus vitae massa bibendum, molestie elit non, consequat sapien. Pellentesque dignissim pretium nisi, vel porta velit porttitor vitae. Ut varius ex tellus, porta elementum massa mattis in. Aliquam erat volutpat. Integer euismod odio in urna accumsan auctor. Morbi pretium augue a erat accumsan vestibulum. Aliquam ac nibh fermentum, aliquet lectus at, convallis sapien. Cras eros enim, tempus vitae mi ac, molestie feugiat magna. Phasellus vitae ante facilisis, imperdiet mi porttitor, euismod justo. Morbi scelerisque scelerisque ante at ultricies. Donec pellentesque mattis augue eu sollicitudin. Curabitur consectetur erat id dui feugiat, a viverra ex egestas. Pellentesque nec sagittis mauris, tincidunt facilisis odio. Mauris neque lacus, vulputate at sapien quis, consequat iaculis tortor. Maecenas molestie, leo in consequat feugiat, nibh magna ultricies massa, ut feugiat tortor ligula vulputate sapien. Sed mi lacus, gravida sed tincidunt at, venenatis eget eros. Ut risus ex, cursus at elit hendrerit, semper ultrices tellus. Maecenas porttitor fringilla sapien, vel vulputate mi lacinia et. Quisque venenatis orci vel magna placerat maximus. Cras bibendum felis ac bibendum eleifend. Suspendisse ullamcorper dictum leo, in ornare turpis dignissim eget.</p>
                    </div>
                </div>
                <div className="planer-block" id="tempestia">
                    <div className="planar-map"><img src={planemap} alt="plane" /></div>
                    <div className="planar-description">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et est ante. Nunc porttitor, diam ac rhoncus pulvinar, mi mauris elementum dui, ut feugiat tellus ex eget ex. Duis vitae ultrices orci, id commodo sapien. Integer sed vehicula nisl. Suspendisse tincidunt ultrices nisi. Aenean dictum arcu vel nisl aliquam, quis imperdiet est eleifend. Nam gravida ligula turpis, ac pulvinar nisl vulputate id. Maecenas ut tempus eros. Duis tempor malesuada lorem, a accumsan diam condimentum non. Suspendisse vitae felis pretium, ultricies lacus quis, convallis libero. Donec ut accumsan justo, a facilisis quam. Sed blandit posuere odio. Quisque ante arcu, finibus eget commodo eu, tempor ut urna. Suspendisse potenti. Aliquam et tempus mauris. Proin nec commodo arcu. Fusce id fermentum est. Nam scelerisque dapibus elit non facilisis. Phasellus vitae massa bibendum, molestie elit non, consequat sapien. Pellentesque dignissim pretium nisi, vel porta velit porttitor vitae. Ut varius ex tellus, porta elementum massa mattis in. Aliquam erat volutpat. Integer euismod odio in urna accumsan auctor. Morbi pretium augue a erat accumsan vestibulum. Aliquam ac nibh fermentum, aliquet lectus at, convallis sapien. Cras eros enim, tempus vitae mi ac, molestie feugiat magna. Phasellus vitae ante facilisis, imperdiet mi porttitor, euismod justo. Morbi scelerisque scelerisque ante at ultricies. Donec pellentesque mattis augue eu sollicitudin. Curabitur consectetur erat id dui feugiat, a viverra ex egestas. Pellentesque nec sagittis mauris, tincidunt facilisis odio. Mauris neque lacus, vulputate at sapien quis, consequat iaculis tortor. Maecenas molestie, leo in consequat feugiat, nibh magna ultricies massa, ut feugiat tortor ligula vulputate sapien. Sed mi lacus, gravida sed tincidunt at, venenatis eget eros. Ut risus ex, cursus at elit hendrerit, semper ultrices tellus. Maecenas porttitor fringilla sapien, vel vulputate mi lacinia et. Quisque venenatis orci vel magna placerat maximus. Cras bibendum felis ac bibendum eleifend. Suspendisse ullamcorper dictum leo, in ornare turpis dignissim eget.</p>
                    </div>
                </div>
                <MainNavi />
            </div>
        );
    }
}

export default Planes;